import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const migration = readFileSync(resolve('supabase/migrations/20260911000385_multichannel_bidirectional_replication.sql'), 'utf8');
const rollback = readFileSync(resolve('supabase/rollbacks/20260911000385_multichannel_bidirectional_replication_rollback.sql'), 'utf8');
const actions = readFileSync(resolve('src/app/actions/multichannel-automations.ts'), 'utf8');
const page = readFileSync(resolve('src/app/(dashboard)/multichannel-automations/page.tsx'), 'utf8');
const cron = readFileSync(resolve('src/app/api/cron/mpm-maintenance/route.ts'), 'utf8');

const has = (source: string, pattern: RegExp, message?: string) => assert.match(source, pattern, message);

test('01 migration incremental 385 existe sem alterar migrations antigas', () => has(migration, /MPM Fase 3/));
test('02 quatro feature flags nascem desligadas', () => assert.equal((migration.match(/'false'::jsonb/g) || []).length, 4));
test('03 kill switch geral está presente', () => has(migration, /multichannel_replication_enabled/));
test('04 flag social para TV está presente', () => has(migration, /social_to_tv_replication_enabled/));
test('05 flag de crosspost está presente', () => has(migration, /social_crosspost_enabled/));
test('06 flag de modo automático está presente', () => has(migration, /multichannel_auto_mode_enabled/));
test('07 regras são isoladas por owner', () => has(migration, /owner_type TEXT NOT NULL CHECK\(owner_type IN\('company','creator'\)\),\s*owner_id UUID NOT NULL/));
test('08 origem aceita MPM TV e social', () => has(migration, /source_kind IN\('mpm','tv','social'\)/));
test('09 padrão da regra exige aprovação', () => has(migration, /mode TEXT NOT NULL DEFAULT 'approval'/));
test('10 regra temporária exige janela válida', () => has(migration, /mode<>'automatic_temporary'[\s\S]*starts_at IS NOT NULL AND ends_at IS NOT NULL/));
test('11 fallback temporário aceita approval ou off', () => has(migration, /fallback_mode IN\('approval','off'\)/));
test('12 timezone explícito é persistido', () => has(migration, /timezone TEXT NOT NULL DEFAULT 'America\/Cuiaba'/));
test('13 todos elegíveis exige confirmação avançada', () => has(migration, /advanced_confirmed/));
test('14 hashtag exige valor', () => has(migration, /eligibility_mode<>'hashtag'[\s\S]*required_hashtag/));
test('15 regra exige ao menos um destino', () => has(migration, /jsonb_array_length[\s\S]*=0[\s\S]*Selecione ao menos um destino/));
test('16 destinos cobrem TV playlist social campanha e rede', () => has(migration, /'tv','playlist','social','campaign_tvs','collaborative_network'/));
test('17 TV residencial é sempre bloqueada', () => has(migration, /residential_allowed=false/));
test('18 trigger valida owner da origem', () => has(migration, /trg_validate_multichannel_rule_owner/));
test('19 trigger valida owner do destino', () => has(migration, /trg_validate_multichannel_target_owner/));
test('20 canal social de destino precisa pertencer ao owner', () => has(migration, /Canal de destino não pertence ao owner/));
test('21 playlist de destino precisa pertencer à empresa', () => has(migration, /Playlist de destino não pertence à empresa/));
test('22 propagation_id é persistido', () => has(migration, /propagation_id UUID NOT NULL DEFAULT gen_random_uuid/));
test('23 raiz de propagação é rastreada', () => has(migration, /root_event_id UUID REFERENCES public\.propagation_events/));
test('24 profundidade padrão é três', () => has(migration, /max_depth SMALLINT NOT NULL DEFAULT 3/));
test('25 excesso de profundidade é bloqueado', () => has(migration, /blocked_depth/));
test('26 destinos visitados impedem loop', () => has(migration, /target_key=ANY[\s\S]*blocked_loop/));
test('27 evento tem idempotência única', () => has(migration, /idempotency_key TEXT NOT NULL UNIQUE/));
test('28 target deduplica evento destino e versão', () => has(migration, /UNIQUE\(event_id,rule_target_id,rule_version\)/));
test('29 hash de conteúdo suporta janela de deduplicação', () => has(migration, /idx_propagation_events_content_window/));
test('30 frequency cap é aplicado', () => has(migration, /blocked_frequency/));
test('31 modo de detecção não inventa realtime', () => has(migration, /'instagram','manual',false,false[\s\S]*'facebook','manual',false,false[\s\S]*'tiktok','manual',false,false/));
test('32 TikTok permanece manual sem publicação aprovada', () => has(migration, /target_provider='tiktok'[\s\S]*'manual'/));
test('33 crosspost automático exige flag e capability', () => has(migration, /social_crosspost_enabled[\s\S]*automatic_publish_capable/));
test('34 conexão social precisa estar ativa e não expirada', () => has(migration, /sc\.status='active'[\s\S]*sc\.expires_at/));
test('35 social para TV exige flag e mídia canônica', () => has(migration, /social_to_tv_replication_enabled[\s\S]*p_media_asset_id IS NULL/));
test('36 TV exige asset aprovado da mesma empresa', () => has(migration, /media_assets WHERE id=e\.media_asset_id AND company_id=t\.owner_id AND status='approved'/));
test('37 publicação social reutiliza campaign_id', () => has(migration, /VALUES\(t\.target_social_channel_id,e\.campaign_id,e\.media_asset_id/));
test('38 rede colaborativa não ignora matching V1', () => has(migration, /requires_v1_matching/));
test('39 propagação nunca cria evento econômico', () => has(migration, /economic_event_created BOOLEAN NOT NULL DEFAULT false CHECK\(economic_event_created=false\)/));
test('40 aprovação possui expiração rejeição e decisão', () => has(migration, /'pending','approved','rejected','expired','ignored'/));
test('41 scheduler implementa retry exponencial e dead-letter', () => has(migration, /dead_letter[\s\S]*power\(2,attempts\)/));
test('42 RLS existe em todas as tabelas operacionais', () => assert.equal((migration.match(/ENABLE ROW LEVEL SECURITY/g) || []).length, 7));
test('43 UI oferece wizard flags fila e capabilities', () => { has(page, /Nova regra/); has(page, /Fila de aprovação/); has(page, /Capabilities observadas/); });
test('44 actions autenticam e usam RPCs seguras', () => { has(actions, /auth\.getUser/); has(actions, /create_multichannel_rule/); has(actions, /decide_multichannel_approval/); });
test('45 cron integra scheduler e rollback é completo', () => { has(cron, /process_multichannel_scheduler/); has(rollback, /DROP TABLE IF EXISTS public\.multichannel_rules/); });
