import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { fingerprint, isFreshTimestamp, maskIdentifier, normalizePhone, verifyPartnerSignature } from '../src/lib/referrals.ts';
import { createHmac } from 'node:crypto';

const sql = fs.readFileSync('supabase/migrations/20260911000382_referral_conversion_commissions_phase2.sql','utf8');
const api = fs.readFileSync('src/app/api/v1/integrations/events/route.ts','utf8');
const leadsApi = fs.readFileSync('src/app/api/v1/integrations/leads/route.ts','utf8');
const landing = fs.readFileSync('src/app/r/[code]/page.tsx','utf8');
const qr = fs.readFileSync('src/app/api/referrals/[code]/qr/route.ts','utf8');

test('reutiliza campaign e campaign_offers sem novo marketplace',()=>{ assert.match(sql,/ALTER TABLE public\.campaigns/); assert.match(sql,/ALTER TABLE public\.campaign_offers/); assert.doesNotMatch(sql,/CREATE TABLE public\.campaigns/); });
test('referral tem código público seguro, link e QR único',()=>{ assert.match(sql,/public_code TEXT NOT NULL UNIQUE/); assert.match(landing,/campaign_referrals/); assert.match(qr,/QRCode\.toString/); });
test('código público não depende de schema externo no search_path',()=>{ assert.match(sql,/replace\(gen_random_uuid\(\)::text/); assert.doesNotMatch(sql,/gen_random_bytes/); });
test('telefone é normalizado e identificador mascarado',()=>{ assert.equal(normalizePhone('+55 (66) 99999-0000'),'5566999990000'); assert.match(maskIdentifier('Maria Silva','66999990000'),/^Ma\*\*\* · \*\*\*0000$/); });
test('Lead canônico preserva atribuição e janela versionada',()=>{ assert.match(sql,/referral_attribution_rule_versions/); assert.match(sql,/trg_referral_lead_attribution_immutable/); assert.match(sql,/attribution_expires_at/); });
test('duplicado vira possible_duplicate e não é apagado',()=>{ assert.match(sql,/validation:='possible_duplicate'/); assert.match(sql,/possible_duplicate_of/); });
test('autoindicação e fraude possuem configuração e flags de risco',()=>{ assert.match(sql,/risk_configuration/); assert.match(sql,/risk_flags TEXT\[\]/); });
test('Creator concorrente não substitui atribuição existente',()=>assert.match(sql,/Atribuição não pode ser trocada automaticamente/));
test('API é versionada, autenticada e exige scope',()=>{ assert.match(api,/x-mpm-key-id/); assert.match(api,/events:write/); });
test('API de Lead é separada, autenticada e exige consentimento',()=>{ assert.match(leadsApi,/x-mpm-key-id/); assert.match(leadsApi,/leads:write/); assert.match(leadsApi,/payload\.consent !== true/); });
test('HMAC válido passa e assinatura inválida falha',()=>{ const body='{"ok":true}',ts=new Date().toISOString(),secret='secret'; const sig=createHmac('sha256',secret).update(`${ts}.${body}`).digest('hex'); assert.equal(verifyPartnerSignature(secret,ts,body,sig),true); assert.equal(verifyPartnerSignature(secret,ts,body,'0'.repeat(64)),false); });
test('timestamp protege replay',()=>{ assert.equal(isFreshTimestamp(new Date().toISOString()),true); assert.equal(isFreshTimestamp('2020-01-01T00:00:00Z'),false); });
test('idempotência externa é única por parceiro',()=>{ assert.match(sql,/UNIQUE\(partner_id,external_event_id\)/); assert.match(api,/deduplicated: true/); });
test('rate limit e outbox com retry/dead-letter existem',()=>{ assert.match(sql,/consume_integration_rate_limit/); assert.match(sql,/integration_outbox/); assert.match(sql,/dead_letter/); assert.match(sql,/attempts INTEGER/); });
test('franquias A e B são tenants isolados por RLS',()=>{ assert.match(sql,/CREATE TABLE public\.franchises/); assert.match(sql,/Franchises tenant read/); assert.match(sql,/franchise_id IN\(SELECT id FROM public\.franchises/); });
test('eventos cobrem Lead, proposta, venda, conversão e cancelamento',()=>{ for(const event of ['lead.created','lead.qualified','proposal.created','sale.confirmed','contract.activated','payment.confirmed','sale.cancelled']) assert.match(sql,new RegExp(event.replace('.','\\.'))); });
test('comissão prevista e elegível são estados distintos',()=>assert.match(sql,/forecast','eligible','invoiced','received','payable','paid'/));
test('venda confirmada materializa forecast antes do gatilho elegível',()=>{ assert.match(sql,/CASE WHEN p_event_type=cfg\.commission_trigger_event THEN 'eligible' ELSE 'forecast'/); assert.match(sql,/event_type,idempotency_key,metadata\)\s+VALUES\(v_commission_id,l\.creator_id,l\.franchise_id,'accrued'/); });
test('gatilho de comissão é configurável',()=>assert.match(sql,/commission_trigger_event/));
test('snapshot padrão 10%, gross, fee e net são congelados',()=>{ assert.match(sql,/mpm_fee_rate NUMERIC\(9,6\) NOT NULL DEFAULT 10/); assert.match(sql,/snapshot JSONB NOT NULL/); assert.match(sql,/creator_net_amount/); });
test('exemplo 500 gera fee 50 e Creator 450',()=>{ const gross=500,fee=Math.round(gross*10)/100; assert.equal(fee,50); assert.equal(gross-fee,450); });
test('comissão suporta fixa, percentual e faixas',()=>assert.match(sql,/fixed','percentage','tiered'/));
test('fechamento é consolidado, configurável e idempotente',()=>{ assert.match(sql,/weekly','biweekly','monthly','manual/); assert.match(sql,/UNIQUE\(franchise_id,period_start,period_end\)/); assert.match(sql,/commission_closing_items/); });
test('contestação e motivos auditáveis existem',()=>assert.match(sql,/existing_lead','incorrect_attribution','cancelled_sale','duplicate_customer','ineligible_sale','other/));
test('recebimento simulado cria payable exato por comissão',()=>{ assert.match(sql,/simulate_commission_receipt/); assert.match(sql,/item\.creator_net_amount/); });
test('ledger financeiro é imutável e reversão é aditiva',()=>{ assert.match(sql,/trg_conversion_commission_ledger_immutable/); assert.match(sql,/reverses_entry_id/); });
test('duas comissões e duas cobranças são bloqueadas',()=>{ assert.match(sql,/sale_id UUID NOT NULL UNIQUE/); assert.match(sql,/idempotency_key TEXT NOT NULL UNIQUE/); });
test('Crédito MPM, Direito de Mídia e comissão TV não são usados',()=>{ assert.doesNotMatch(sql,/INSERT INTO public\.wallet_ledger/); assert.doesNotMatch(sql,/INSERT INTO public\.media_right_ledger/); assert.doesNotMatch(sql,/INSERT INTO public\.recurring_commissions/); });
test('dados privados do Lead não vão ao funil Creator',()=>{ const fn=sql.slice(sql.indexOf('CREATE OR REPLACE FUNCTION public.get_my_referral_funnel'),sql.indexOf('DO $$ DECLARE t TEXT')); assert.doesNotMatch(fn,/encrypted_contact|phone_hash|document_hash/); });
test('billing e payout reais começam OFF e simulação é default',()=>{ assert.match(sql,/'commission_billing_enabled','false'/); assert.match(sql,/'creator_cash_payout_enabled','false'/); assert.match(sql,/simulation_only BOOLEAN NOT NULL DEFAULT true/); });
test('flags operacionais falham fechadas também no banco',()=>{ assert.match(sql,/mpm_feature_enabled\('creator_referral_leads_enabled'\)/); assert.match(sql,/mpm_feature_enabled\('conversion_commissions_enabled'\)/); assert.match(api,/external_lead_api_enabled/); });
test('evento de venda exige identificador externo para idempotência',()=>assert.match(sql,/external_sale_id é obrigatório para eventos de venda/));
test('cálculo recebe UUID da regra e evita variável ambígua',()=>{ assert.match(sql,/calculate_conversion_commission\(rule\.id,/); assert.match(sql,/v_commission_id UUID/); });
test('fingerprint não expõe contato',()=>assert.equal(fingerprint('secret').length,64));
