import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { capacitySummary, certifiedCapacity, commercialSplit, equivalentSlots, mediaRightRelease, minutesForPeriod, nextDynamicItem, sellableInventory } from '../src/lib/mpm/screen-capacity.ts';

const migration=fs.readFileSync(path.join(process.cwd(),'supabase/migrations/20260912000389_screen_capacity_economic_engine.sql'),'utf8');
const rollback=fs.readFileSync(path.join(process.cwd(),'supabase/rollbacks/20260912000389_screen_capacity_economic_engine_rollback.sql'),'utf8');
const weekdays=(hours:number)=>[1,2,3,4,5].map(weekday=>({weekday,startMinute:8*60,endMinute:(8+hours)*60}));

test('15 segundos equivalem a uma unidade',()=>assert.equal(equivalentSlots(.25),1));
test('30 segundos equivalem a duas unidades',()=>assert.equal(equivalentSlots(.5),2));
test('8h em cinco dias geram 9.600 slots semanais',()=>assert.equal(equivalentSlots(minutesForPeriod(new Date('2026-09-07'),new Date('2026-09-11'),weekdays(8))),9600));
test('10h em cinco dias geram 12.000 slots',()=>assert.equal(equivalentSlots(minutesForPeriod(new Date('2026-09-07'),new Date('2026-09-11'),weekdays(10))),12000));
test('15h em cinco dias geram 18.000 slots',()=>assert.equal(equivalentSlots(minutesForPeriod(new Date('2026-09-07'),new Date('2026-09-11'),weekdays(15))),18000));
test('mês curto e longo usam dias reais',()=>assert.ok(minutesForPeriod(new Date('2026-02-01'),new Date('2026-02-28'),weekdays(8))<minutesForPeriod(new Date('2026-03-01'),new Date('2026-03-31'),weekdays(8))));
test('exceção substitui agenda do dia',()=>assert.equal(minutesForPeriod(new Date('2026-09-07'),new Date('2026-09-07'),weekdays(8),{'2026-09-07':120}),120));
test('plano padrão pesado compromete 35.000 equivalentes',()=>assert.equal(capacitySummary(10400,{network:20000,ownPieces:5000,ownMaxSeconds:30,mpmReserve:2000,sponsor:0,commercial:3000}).committed,35000));
test('sobra técnica é calculada sem hardcode universal',()=>assert.equal(capacitySummary(10400,{network:20000,ownPieces:5000,ownMaxSeconds:30,mpmReserve:2000,sponsor:0,commercial:3000}).surplus,6600));
test('vendável é o menor entre nominal e executável',()=>assert.equal(sellableInventory(3000,1300,1420),1420));
test('filler não reduz inventário comercial',()=>assert.equal(sellableInventory(3000,0,5000),3000));
test('venda total zera disponibilidade',()=>assert.equal(sellableInventory(3000,3000,5000),0));
test('primeiro ciclo libera integralmente',()=>assert.equal(mediaRightRelease(20000,1,0),20000));
test('segundo ciclo 100% disponível libera integralmente',()=>assert.equal(mediaRightRelease(20000,2,100),20000));
test('segundo ciclo 50% usa regra híbrida 30/70',()=>assert.equal(mediaRightRelease(20000,2,50),13000));
test('falta de demanda não entra no cálculo de disponibilidade',()=>assert.equal(mediaRightRelease(18000,2,100),18000));
test('um pico não certifica capacidade',()=>assert.equal(certifiedCapacity([100000],30,15),null));
test('30 dias estáveis certificam com margem',()=>assert.equal(certifiedCapacity(Array(30).fill(1000),30,15),850));
test('certificação não supera o menor dia estável',()=>assert.equal(certifiedCapacity([...Array(29).fill(1000),700],30,10),700));
test('venda aplica taxa 10% e owner 90%',()=>assert.deepEqual(commercialSplit(75000),{grossCents:75000,platformCents:7500,ownerCents:67500,selfPurchase:false}));
test('uso próprio não gera remuneração',()=>assert.deepEqual(commercialSplit(75000,10,true),{grossCents:75000,platformCents:0,ownerCents:0,selfPurchase:true}));
test('grade prioriza contrato com prazo',()=>assert.equal(nextDynamicItem([{id:'rede',bucket:'network',pending:5},{id:'venda',bucket:'sold',pending:5,deadline:1}],{})?.id,'venda'));
test('grade evita starvation pelo progresso relativo',()=>assert.equal(nextDynamicItem([{id:'a',bucket:'network',pending:10},{id:'b',bucket:'own',pending:10}],{a:9,b:1})?.id,'b'));
test('grade vazia permite filler externo',()=>assert.equal(nextDynamicItem([],{}),null));
test('migration reutiliza núcleo canônico',()=>{for(const name of ['inventory_capacity_periods','media_inventory','partner_programs','media_right'])assert.match(migration,new RegExp(name));});
test('plano padrão preserva 20k/5k/2k/3k e 600 promocionais',()=>assert.match(migration,/14900,20000,5000,2000,0,3000,600/));
test('Racon preserva 18k + 2k sponsor dentro de 30k nominal',()=>assert.match(migration,/9990,18000,5000,2000,2000,3000,0/));
test('Racon começa com dez cupons gratuitos de uso único',()=>{assert.match(migration,/generate_series\(1,10\)/);assert.match(migration,/code TEXT NOT NULL UNIQUE/);});
test('flags econômicas e cobrança real começam desligadas',()=>{assert.match(migration,/real_inventory_billing_enabled','false'/);assert.match(migration,/real_inventory_payout_enabled','false'/);});
test('agenda, exceções, diário e certificação existem',()=>{for(const table of ['screen_operating_schedules','screen_schedule_exceptions','screen_capacity_daily','screen_capacity_certifications'])assert.match(migration,new RegExp(`CREATE TABLE public\\.${table}`));});
test('RLS mantém isolamento por empresa',()=>assert.match(migration,/get_user_company_ids\(\)/));
test('rollback acompanha a migration',()=>assert.match(rollback,/screen_capacity_plan_versions/));
