'use client';

import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Building2, CircleDollarSign, Monitor, Network, QrCode, Sparkles, Target, TrendingUp, Tv, Users } from 'lucide-react';
import { useState } from 'react';

function SectionTitle({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="max-w-3xl"><p className="mb-4 text-[11px] font-black uppercase tracking-[.22em] text-cyan-300">{eyebrow}</p><h2 className="text-balance text-3xl font-black leading-[1.02] tracking-[-.05em] text-white sm:text-5xl">{title}</h2>{text && <p className="mt-5 text-base leading-7 text-slate-400 sm:text-lg">{text}</p>}</div>;
}

function DemoTag() { return <span className="inline-flex rounded-full border border-amber-300/30 bg-amber-300/[.1] px-2.5 py-1 text-[9px] font-black uppercase tracking-[.13em] text-amber-200">Simulação</span>; }

const wa = 'https://wa.me/5566996086030?text=Ol%C3%A1!%20Quero%20conhecer%20o%20Programa%20Racon%20%2B%20M%C3%ADdia%20por%20M%C3%ADdia.';

export default function RaconLanding() {
  const [screens, setScreens] = useState(10);
  const [newSales, setNewSales] = useState(1);
  const [margin, setMargin] = useState(1000);
  const [ownMedia, setOwnMedia] = useState(0);
  const [otherRevenue, setOtherRevenue] = useState(0);
  const eligibleValue = newSales * margin + ownMedia + otherRevenue;
  const balance = eligibleValue - 1000;
  const partnerGross = screens * 750;

  return <main className="min-h-screen overflow-x-hidden bg-[#06111f] text-white selection:bg-cyan-200 selection:text-[#06111f]">
    <header className="sticky top-0 z-50 border-b border-white/[.08] bg-[#06111f]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><Link href="/" className="flex items-center gap-2 font-black"><span className="grid h-9 w-9 place-items-center overflow-hidden rounded-xl bg-white p-0.5"><Image src="/brand/midia-por-midia-logo.png" alt="Mídia por Mídia" width={64} height={64} /></span><span className="hidden sm:inline">Mídia por Mídia</span><span className="text-slate-500">×</span><span className="text-cyan-300">Racon</span></Link><a href="#conhecer" className="rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-black text-[#06111f] transition hover:bg-white">Quero conhecer</a></div></header>

    <section className="relative isolate px-4 pb-20 pt-20 sm:px-6 sm:pb-28 sm:pt-28"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_70%_10%,rgba(34,211,238,.17),transparent_27%),linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:auto,50px_50px,50px_50px]" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><div className="mb-7 flex flex-wrap gap-2"><span className="rounded-full border border-cyan-300/25 bg-cyan-300/[.08] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] text-cyan-200">Programa Racon + Mídia por Mídia</span><DemoTag /></div><h1 className="max-w-4xl text-balance text-5xl font-black leading-[.94] tracking-[-.065em] sm:text-6xl lg:text-7xl">Sua empresa pode ser cliente da Racon. <span className="bg-gradient-to-r from-cyan-200 to-blue-400 bg-clip-text text-transparent">E também fazer parte de uma nova Rede de mídia.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Clientes e parceiros Racon podem conectar suas TVs à Mídia por Mídia, divulgar seus negócios, acessar mídia em outros pontos e participar de novas oportunidades comerciais.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#conhecer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-cyan-300 px-5 text-sm font-black text-[#06111f] hover:bg-white">Quero conhecer <ArrowRight className="h-4 w-4" /></a><a href={wa} target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/15 px-5 text-sm font-black hover:border-cyan-300/50">Sou cliente Racon</a></div></div><div className="rounded-[32px] border border-white/10 bg-[#091827]/90 p-5 shadow-2xl sm:p-7"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase tracking-[.17em] text-cyan-300">Uma relação que cresce</p><Network className="h-6 w-6 text-cyan-300" /></div><div className="my-8 grid grid-cols-2 gap-3 text-center sm:grid-cols-3">{[[Building2,'Racon'],[Users,'Empresários'],[Tv,'TVs'],[Sparkles,'Creators'],[Monitor,'Clientes'],[TrendingUp,'Indicações']].map(([Icon,label]) => { const I = Icon as typeof Tv; return <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><I className="mx-auto h-5 w-5 text-cyan-300"/><p className="mt-2 text-xs font-black">{String(label)}</p></div>; })}</div><div className="rounded-2xl border border-cyan-300/25 bg-cyan-300/[.07] p-5"><p className="text-sm font-black">A Racon deixa de comprar apenas audiência.</p><p className="mt-1 text-sm text-slate-300">Ela começa a construir uma Rede de presença, relacionamentos e oportunidades.</p></div></div></div></section>

    <section className="border-y border-white/[.07] bg-[#081625] px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Para clientes e parceiros" title="Uma TV pode virar uma nova frente de comunicação e negócio." /><div className="mt-11 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[Tv,'Tenha sua própria TV','Use para promoções, ofertas, vídeos e comunicação.'],[Network,'Troque mídia','Participe da Rede e conquiste Direito de Mídia conforme o programa.'],[CircleDollarSign,'Comercialize','Parte da capacidade elegível pode virar inventário comercial.'],[Users,'Encontre Creators','Amplie campanhas com mídia social e conteúdo local.'],[Target,'Gere oportunidades','Campanhas, indicações, promoções e novos relacionamentos.'],[Building2,'Divulgue sua empresa','Sua campanha pode circular em outros pontos elegíveis da Rede.']].map(([Icon,title,text]) => { const I=Icon as typeof Tv; return <article key={String(title)} className="rounded-[25px] border border-white/10 bg-[#06111f] p-6"><I className="h-6 w-6 text-cyan-300"/><h3 className="mt-6 text-xl font-black">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{String(text)}</p></article>; })}</div></div></section>

    <section className="px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Programa inicial" title="10 cupons para 10 TVs parceiras." text="A franquia que contrata o Sistema Racon recebe a referência de 10 cupons para destinar a clientes, empresários, parceiros e relacionamentos estratégicos. Elegibilidade e isenção seguem as regras comerciais vigentes do programa." /><div className="mt-12 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><article className="rounded-[30px] border border-cyan-300/35 bg-cyan-300/[.08] p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">TV parceira Racon</p><strong className="mt-4 block text-6xl font-black tracking-[-.07em]">30.000</strong><p className="mt-1 text-sm text-slate-400">inserções nominais de referência*</p><div className="mt-7 space-y-3 text-sm">{[['5.000','Mídia própria da empresa'],['18.000','Direito de Mídia da empresa / Rede'],['2.000','Presença Racon'],['2.000','Reserva MPM'],['3.000','Inventário comercial']].map(([n,l]) => <div key={l} className="flex justify-between gap-4 border-b border-white/10 pb-3"><b className="text-cyan-200">{n}</b><span className="text-right text-slate-300">{l}</span></div>)}</div><p className="mt-6 text-xs leading-5 text-slate-500">*Capacidade, duração e distribuição seguem o motor e as regras reais da plataforma.</p></article><article className="rounded-[30px] border border-white/10 bg-[#091827] p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Presença de marca, não audiência humana</p><h3 className="mt-4 text-3xl font-black">Cada TV parceira reserva 2.000 inserções/mês para a Racon.</h3><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{[10,50,100,500].map(n => <div key={n} className="rounded-2xl bg-white/[.05] p-4"><strong className="block text-2xl font-black text-cyan-300">{n}</strong><span className="text-xs text-slate-500">TVs</span><p className="mt-3 text-sm font-black">{(n*2000).toLocaleString('pt-BR')}</p><span className="text-[10px] text-slate-500">inserções/mês</span></div>)}</div><p className="mt-7 text-sm leading-6 text-slate-400">Quanto mais parceiros entram, maior fica a capacidade de divulgação da própria Rede — reduzindo a dependência de mídia paga tradicional ao transformar parceiros em pontos de expansão.</p></article></div></div></section>

    <section className="border-y border-white/[.07] bg-[#081625] px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Cliente Racon → parceiro" title="Um cliente pode se transformar em um ponto de expansão." /><div className="mt-10 grid gap-3 md:grid-cols-5">{['Participa com a Racon','Conhece o benefício MPM','Conecta uma TV','Divulga sua empresa','Indica novos empresários'].map((item,i) => <div key={item} className="relative rounded-2xl border border-white/10 bg-[#06111f] p-5"><span className="text-xs font-black text-cyan-300">0{i+1}</span><p className="mt-4 text-sm font-bold leading-6">{item}</p>{i < 4 && <ArrowRight className="absolute -right-5 top-1/2 z-10 hidden h-5 w-5 text-cyan-300 md:block"/>}</div>)}</div><div className="mt-10 rounded-[28px] border border-white/10 bg-[#06111f] p-6 sm:flex sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Reuniões Racon</p><h3 className="mt-2 text-2xl font-black">Além da solução de consórcio, um benefício para empresários parceiros.</h3></div><div className="mt-5 flex items-center gap-3 sm:mt-0"><QrCode className="h-12 w-12 text-cyan-300"/><p className="text-sm font-bold text-slate-300">Aponte para<br/><b className="text-white">midiapormidia.com.br/racon</b></p></div></div></div></section>

    <section id="conhecer" className="px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-center justify-between gap-5"><SectionTitle eyebrow="Simulador de perspectiva" title="Quanto negócio elegível precisa ser gerado para a tecnologia se pagar?" text="Simulação para conversa executiva. Não representa receita garantida, cobrança, venda ou dado de produção." /><DemoTag /></div><div className="mt-11 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-[30px] border border-white/10 bg-[#091827] p-6 sm:p-8"><p className="text-sm font-black">Ajuste o cenário</p><div className="mt-7 space-y-5">{[["Novas vendas geradas",newSales,setNewSales,0,20,1,'vendas'],['Margem/comissão Racon',margin,setMargin,0,10000,100,'R$'],['Receita de mídia própria',ownMedia,setOwnMedia,0,10000,100,'R$'],['Outras receitas elegíveis',otherRevenue,setOtherRevenue,0,10000,100,'R$']].map(([label,value,setter,min,max,step,suffix]) => <label key={String(label)} className="block"><span className="flex justify-between text-xs font-bold text-slate-300"><span>{String(label)}</span><b className="text-cyan-300">{String(suffix)==='R$' ? `R$ ${Number(value).toLocaleString('pt-BR')}` : `${value} ${suffix}`}</b></span><input aria-label={String(label)} type="range" min={Number(min)} max={Number(max)} step={Number(step)} value={Number(value)} onChange={e => (setter as (n:number)=>void)(Number(e.target.value))} className="mt-3 w-full accent-cyan-300"/></label>)}</div></div><div className="rounded-[30px] border border-cyan-300/30 bg-cyan-300/[.07] p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Resultado ilustrativo mensal</p><h3 className="mt-3 text-3xl font-black">Custo × valor incremental</h3></div><DemoTag /></div><div className="mt-8 grid gap-3 sm:grid-cols-3">{[['Custo tecnologia','R$ 1.000'],['Valor elegível',`R$ ${eligibleValue.toLocaleString('pt-BR')}`],['Diferença',`${balance >= 0 ? '+' : '-'} R$ ${Math.abs(balance).toLocaleString('pt-BR')}`]].map(([label,value],i) => <div key={label} className={`rounded-2xl p-5 ${i===2 ? (balance >= 0 ? 'bg-emerald-300 text-[#06111f]' : 'bg-amber-300 text-[#06111f]') : 'bg-[#06111f]/70'}`}><p className="text-[10px] font-black uppercase tracking-[.12em] opacity-70">{label}</p><strong className="mt-2 block text-2xl font-black">{value}</strong></div>)}</div><p className="mt-8 text-sm leading-6 text-slate-300">A pergunta deixa de ser “quanto custa o sistema?” e passa a ser “quanto negócio ele precisa gerar para se pagar?”</p><p className="mt-4 border-t border-white/10 pt-4 text-xs leading-5 text-slate-500">Receita de TVs parceiras não entra neste cálculo: a participação do proprietário segue pertencendo ao proprietário, conforme regras vigentes. Apenas mídia própria, novas vendas e mecanismos comerciais formalmente definidos são elegíveis.</p></div></div></div></section>

    <section className="border-y border-white/[.07] bg-[#081625] px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Transparência econômica" title="O valor da TV parceira continua sendo do parceiro." text="Uma referência de 3.000 inserções comerciais × R$ 0,25 equivale a R$ 750 de comercialização bruta potencial por TV; a participação de 90% é do proprietário elegível antes de impostos e tarifas. Isso não é receita automática da Racon." /><div className="mt-7 max-w-md"><label className="block text-xs font-black text-slate-300">Cenário de TVs parceiras: <span className="text-cyan-300">{screens} TVs</span><input aria-label="Cenário de TVs parceiras" type="range" min="1" max="100" step="1" value={screens} onChange={e => setScreens(Number(e.target.value))} className="mt-3 w-full accent-cyan-300"/></label></div><div className="mt-9 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-[#06111f] p-6"><p className="text-xs font-black text-slate-500">{screens} TVs — referência</p><strong className="mt-3 block text-4xl font-black text-cyan-300">R$ {partnerGross.toLocaleString('pt-BR')}</strong><p className="mt-2 text-xs text-slate-400">potencial bruto de comercialização</p></div><div className="rounded-2xl border border-white/10 bg-[#06111f] p-6"><p className="text-xs font-black text-slate-500">90% aos proprietários</p><strong className="mt-3 block text-4xl font-black text-cyan-300">R$ {(partnerGross*.9).toLocaleString('pt-BR')}</strong><p className="mt-2 text-xs text-slate-400">potencial, antes de impostos/tarifas</p></div><div className="rounded-2xl border border-cyan-300/30 bg-cyan-300/[.08] p-6"><p className="text-xs font-black text-cyan-200">A regra essencial</p><strong className="mt-3 block text-xl font-black">Não desviar a receita do parceiro.</strong><p className="mt-2 text-xs leading-5 text-slate-300">O ecossistema pode criar valor acima do custo da tecnologia sem confundir receitas.</p></div></div></div></section>

    <section className="px-4 py-20 sm:px-6 sm:py-28"><div className="mx-auto max-w-5xl rounded-[36px] bg-cyan-300 p-8 text-[#06111f] sm:p-14"><p className="text-xs font-black uppercase tracking-[.18em]">Programa Racon + Mídia por Mídia</p><h2 className="mt-5 text-balance text-4xl font-black leading-[.98] tracking-[-.06em] sm:text-6xl">A Racon ajuda o parceiro. O parceiro ajuda a Rede a crescer. A Rede amplia a presença da Racon.</h2><p className="mt-6 max-w-3xl text-base font-semibold leading-7 text-[#06111f]/75">Converse com a equipe para conhecer as regras vigentes, elegibilidade e formatos comerciais do programa.</p><a href={wa} target="_blank" rel="noreferrer" className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#06111f] px-5 text-sm font-black text-white">Quero conhecer o programa <ArrowRight className="h-4 w-4"/></a></div></section>

    <footer className="border-t border-white/[.07] px-4 py-8 text-center text-xs text-slate-500">Mídia por Mídia · Programa conceitual sujeito às regras e capacidades vigentes. Nenhuma promessa de renda, audiência ou resultado.</footer>
  </main>;
}
