import Link from 'next/link';
import { Building2, ChevronRight, Smartphone, Users } from 'lucide-react';

const profiles = [
  { icon: Smartphone, title: 'Sou pessoa física', text: 'Quero usar minha TV, minha rede social e meus contatos para participar da Rede.', items: ['TV residencial', 'Redes sociais', 'Benefícios e indicações'], href: '/organic/register', action: 'Participar como pessoa' },
  { icon: Building2, title: 'Sou empresário', text: 'Quero minha empresa aparecendo em vários pontos e participando de uma Rede de mídia.', items: ['TVs e campanhas', 'Direito de Mídia', 'Comercialização elegível'], href: '/empresa/cadastro', action: 'Cadastrar minha empresa' },
  { icon: Users, title: 'Sou Creator', text: 'Quero ser encontrado e iniciar contratações com empresas e agências.', items: ['Pacotes e conteúdo', 'Empresas e oportunidades', 'Vitrine comercial'], href: '/organic/register', action: 'Criar meu acesso' },
] as const;

export default function ParticipatePage() {
  return <main className="min-h-screen bg-[#06111f] px-4 py-10 text-white sm:px-6 sm:py-16"><div className="mx-auto max-w-6xl"><Link href="/" className="text-sm font-bold text-cyan-300 hover:text-white">← Voltar ao site</Link><div className="mx-auto mt-12 max-w-3xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Quero fazer parte da Rede</p><h1 className="mt-4 text-balance text-4xl font-black tracking-[-.05em] sm:text-6xl">Como você quer participar da Mídia por Mídia?</h1><p className="mt-5 text-lg leading-8 text-slate-400">Escolha seu perfil. Você poderá adicionar outras formas de participação depois, conforme elegibilidade e programas disponíveis.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-4 md:grid-cols-3">{profiles.map(({ icon: Icon, title, text, items, href, action }) => <article key={title} className="flex min-w-0 flex-col rounded-[28px] border border-white/10 bg-white/[.035] p-6 sm:p-8"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/[.1] text-cyan-300"><Icon className="h-6 w-6"/></span><h2 className="mt-6 text-2xl font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p><ul className="mt-6 flex-1 space-y-2 border-t border-white/10 pt-5">{items.map(item => <li key={item} className="text-sm font-bold text-slate-200">• {item}</li>)}</ul><Link href={href} className="mt-7 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-cyan-300 px-4 text-sm font-black text-[#06111f] hover:bg-white">{action}<ChevronRight className="h-4 w-4"/></Link></article>)}</div><div className="mx-auto mt-10 max-w-3xl rounded-2xl border border-cyan-300/20 bg-cyan-300/[.05] p-5 text-center"><p className="text-lg font-black">Todo Líder Creator começa como Creator.</p><p className="mt-2 text-sm leading-6 text-slate-400">Entre para a Rede, conheça o modelo e construa sua primeira equipe de Creators. A liderança depende do programa e das validações aplicáveis.</p><Link href="/programa-lider" className="mt-4 inline-flex text-sm font-black text-cyan-300 hover:text-white">Conhecer o Programa Líder Creator <ChevronRight className="ml-1 h-4 w-4"/></Link></div><p className="mx-auto mt-10 max-w-2xl text-center text-sm leading-6 text-slate-500">Você não precisa ter empresa para fazer parte. Participe com sua TV, audiência, conteúdo ou contatos. Perfis avançados e permissões adicionais seguem as regras de validação da Rede.</p></div></main>;
}
