import { notFound, redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { versionExpansionCommissionAction, versionExpansionPlanAction } from '@/app/actions/expansion';

const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value/100);
const Input=({name,label,value,type='number',step='1'}:{name:string;label:string;value:any;type?:string;step?:string})=><label className="text-xs text-slate-400">{label}<input name={name} type={type} step={step} defaultValue={value??''} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"/></label>;

export default async function ExpansionAdminPage(){
 const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)redirect('/login');
 const {data:profile}=await (supabase.from('profiles') as any).select('is_master_admin').eq('id',user.id).maybeSingle(); if(!profile?.is_master_admin)notFound();
 const [{data:plans},{data:rule},{data:affiliates},{data:subscriptions},{data:payments},{data:commissions}]=await Promise.all([
  (supabase.from('expansion_plans') as any).select('*,expansion_plan_versions(*)').order('display_order'),
  (supabase.from('expansion_commission_rule_versions') as any).select('*').is('effective_to',null).maybeSingle(),
  (supabase.from('affiliate_profiles') as any).select('id,display_name,attribution_code,status,metadata').order('display_name'),
  (supabase.from('company_plan_subscriptions') as any).select('id,status,requested_screens,contracted_amount_cents,companies(trade_name),expansion_plans(name)').order('created_at',{ascending:false}).limit(50),
  (supabase.from('expansion_payments') as any).select('id,status,amount_cents,payment_kind,created_at').order('created_at',{ascending:false}).limit(50),
  (supabase.from('expansion_commission_entries') as any).select('id,status,amount_cents,beneficiary_role,entry_kind,affiliate_profiles(display_name)').order('created_at',{ascending:false}).limit(100),
 ]);
 return <div className="mx-auto max-w-7xl space-y-8"><header><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Master · MPM</p><h1 className="mt-2 text-3xl font-black text-white">Expansão da rede</h1><p className="mt-1 text-sm text-slate-400">Planos, programa Creator, equipe, TVs, cobranças, comissões e onboarding em uma única área.</p></header>
 <section><h2 className="mb-4 text-xl font-bold text-white">Planos versionados</h2><div className="grid gap-5 lg:grid-cols-2">{(plans||[]).map((plan:any)=>{const v=(plan.expansion_plan_versions||[]).find((x:any)=>!x.effective_to);if(!v)return null;return <form key={plan.id} action={async(fd)=>{'use server';await versionExpansionPlanAction(fd)}} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><input type="hidden" name="plan_id" value={plan.id}/><div className="grid gap-3 sm:grid-cols-2"><Input name="name" label="Nome" type="text" value={plan.name}/><Input name="description" label="Descrição" type="text" value={plan.description}/><Input name="included_screens" label="TVs incluídas" value={v.included_screens}/><Input name="monthly_price" label="Mensal (R$)" value={v.monthly_price_cents/100} step="0.01"/><Input name="annual_price" label="Anual (R$)" value={v.annual_price_cents? v.annual_price_cents/100:''} step="0.01"/><Input name="extra_screen_price" label="TV adicional (R$)" value={v.extra_screen_price_cents/100} step="0.01"/><Input name="max_screens" label="Máximo de TVs (vazio = livre)" value={v.max_screens}/><Input name="days_until_second_charge" label="Dias até 2ª cobrança" value={v.days_until_second_charge}/><Input name="grace_days" label="Tolerância inadimplência" value={v.grace_days}/><Input name="preferred_location_limit" label="Locais preferenciais" value={v.preferred_location_limit}/><Input name="company_included_insertions" label="Inserções da empresa" value={v.company_included_insertions}/><Input name="creator_insertions_per_screen" label="Inserções Creator/TV" value={v.creator_insertions_per_screen}/><Input name="creator_entitlement_months" label="Vigência mídia Creator (meses)" value={v.creator_entitlement_months}/><label className="text-xs text-slate-400">Status<select name="status" defaultValue={plan.status} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white"><option>active</option><option>paused</option><option>draft</option><option>archived</option></select></label></div><div className="mt-4 flex gap-5 text-xs text-slate-300"><label><input name="public_available" type="checkbox" defaultChecked={plan.public_available}/> Público</label><label><input name="featured" type="checkbox" defaultChecked={plan.featured}/> Destaque</label></div><button className="mt-4 rounded-xl bg-amber-400 px-4 py-2 text-sm font-black text-slate-950">Salvar como versão {v.version+1}</button></form>})}</div></section>
 {rule&&<section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="text-xl font-bold text-white">Programa Creator · regra versão {rule.version}</h2><p className="mt-1 text-xs text-slate-400">Toda mudança cria uma nova versão; contratos antigos mantêm o snapshot.</p><form action={async(fd)=>{'use server';await versionExpansionCommissionAction(fd)}} className="mt-4 grid gap-3 sm:grid-cols-3"><Input name="first_platform_percent" label="1ª cobrança · MPM %" value={rule.first_platform_percent} step="0.0001"/><Input name="first_creator_percent" label="1ª cobrança · Creator %" value={rule.first_creator_percent} step="0.0001"/><Input name="first_leader_percent" label="1ª cobrança · Líder %" value={rule.first_leader_percent} step="0.0001"/><Input name="recurring_platform_percent" label="Recorrente · MPM %" value={rule.recurring_platform_percent} step="0.0001"/><Input name="recurring_creator_percent" label="Recorrente · Creator %" value={rule.recurring_creator_percent} step="0.0001"/><Input name="recurring_leader_percent" label="Recorrente · Líder %" value={rule.recurring_leader_percent} step="0.0001"/><Input name="duration_months" label="Duração (meses)" value={rule.duration_months}/><button className="self-end rounded-xl bg-purple-500 px-4 py-2 text-sm font-bold text-white">Versionar regra</button></form></section>}
 <section className="grid gap-5 lg:grid-cols-2"><Panel title="Líderes e Creators" rows={(affiliates||[]).map((a:any)=>`${a.display_name} · ${a.attribution_code} · ${a.status}`)}/><Panel title="Empresas / TVs" rows={(subscriptions||[]).map((s:any)=>`${s.companies?.trade_name||'Empresa'} · ${s.expansion_plans?.name||'Plano'} · ${s.requested_screens} TVs · ${s.status}`)}/><Panel title="Cobranças" rows={(payments||[]).map((p:any)=>`${p.payment_kind} · ${money(p.amount_cents)} · ${p.status}`)}/><Panel title="Comissões" rows={(commissions||[]).map((c:any)=>`${c.affiliate_profiles?.display_name||'MPM'} · ${c.beneficiary_role} · ${money(c.amount_cents)} · ${c.status}`)}/></section></div>
}
function Panel({title,rows}:{title:string;rows:string[]}){return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-bold text-white">{title}</h2><div className="mt-4 max-h-80 space-y-2 overflow-auto">{rows.length?rows.map((r,i)=><p key={i} className="rounded-xl bg-slate-950 p-3 text-xs text-slate-300">{r}</p>):<p className="py-5 text-sm text-slate-500">Nenhum registro.</p>}</div></div>}
