'use client';
import Link from 'next/link';
import { AlertTriangle, CheckCircle2, Gauge, TrendingUp } from 'lucide-react';

export function ScreenCapacityOverview({data}:{data:any}){
  if(!data?.success||!data.screens?.length)return null;
  const inventories=new Map((data.inventories||[]).map((i:any)=>[i.source_id,i.id]));
  const cycles=new Map();for(const cycle of data.cycles||[]){if(!cycles.has(cycle.media_inventory_id))cycles.set(cycle.media_inventory_id,cycle);}
  return <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5 sm:p-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 font-bold text-white"><Gauge className="h-5 w-5 text-purple-400"/>Compromisso da sua TV com a Rede</h2><p className="mt-1 text-xs text-slate-500">Disponibilidade mede se a TV permaneceu ligada no horário combinado; entrega da Rede é contabilizada separadamente.</p></div><Link href="/network-inventory" className="text-xs font-black text-purple-400">VER CAPACIDADE</Link></div><div className="grid gap-3 lg:grid-cols-2">{data.screens.map((screen:any)=>{const cycle:any=cycles.get(inventories.get(screen.id));const planned=Number(cycle?.planned_minutes||0);const actual=Number(cycle?.available_minutes||0);const pct=planned?actual/planned*100:0;const bar=pct>=90?'bg-emerald-500':pct>=75?'bg-amber-500':'bg-rose-500';return <article key={screen.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4"><div className="flex justify-between gap-3"><div><b className="text-white">{screen.name}</b><p className="text-xs text-slate-500">{planned?`${(planned/60).toFixed(1)}h programadas · ${(actual/60).toFixed(1)}h disponíveis`:'Ciclo de capacidade ainda não calculado'}</p></div>{pct>=90?<CheckCircle2 className="h-5 w-5 text-emerald-400"/>:pct>0?<AlertTriangle className="h-5 w-5 text-amber-400"/>:<TrendingUp className="h-5 w-5 text-slate-500"/>}</div>{cycle&&<><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full ${bar}`} style={{width:`${Math.min(100,pct)}%`}}/></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><Metric label="Cumprimento" value={`${pct.toFixed(1)}%`}/><Metric label="Direito liberado" value={Number(cycle.rights_released||0).toLocaleString('pt-BR')}/><Metric label="Meta do ciclo" value={Number(cycle.rights_target||0).toLocaleString('pt-BR')}/></div></>}</article>})}</div></section>
}
function Metric({label,value}:{label:string;value:string}){return <div><span className="block text-slate-500">{label}</span><b className="text-slate-200">{value}</b></div>}
