import { NextRequest, NextResponse } from 'next/server';
import { timingSafeEqual } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import pg from 'pg';
export const runtime='nodejs'; export const dynamic='force-dynamic';
const VERSION='20260911000386'; const FILE=`${VERSION}_multichannel_homologation_allowlist.sql`; const KEY='mpm-f31-20260911-6d8a0e74-5a80-4f78-9d0b-65ca7db8a9e2';
function ok(v:string|null){if(!v)return false;const a=Buffer.from(v),b=Buffer.from(KEY);return a.length===b.length&&timingSafeEqual(a,b)}
export async function POST(req:NextRequest){if(!ok(req.headers.get('x-mpm-migration-key')))return NextResponse.json({success:false},{status:401});const raw=process.env.POSTGRES_URL_NON_POOLING||process.env.POSTGRES_URL;if(!raw)return NextResponse.json({success:false,error:'Postgres indisponível.'},{status:500});let cs=raw;try{const u=new URL(raw);u.searchParams.delete('sslmode');cs=u.toString()}catch{}const c=new pg.Client({connectionString:cs,ssl:{rejectUnauthorized:false}});try{await c.connect();const applied=await c.query('SELECT version FROM supabase_migrations.schema_migrations ORDER BY version DESC LIMIT 2');const max=applied.rows[0]?.version;if(max!=='20260911000385'&&max!=='20260911000386')return NextResponse.json({success:false,error:'Estado de migration inesperado.',latest:max},{status:409});if(max==='20260911000386')return NextResponse.json({success:true,alreadyApplied:true,version:VERSION});await c.query('BEGIN');await c.query(readFileSync(join(process.cwd(),'supabase','migrations',FILE),'utf8'));await c.query('INSERT INTO supabase_migrations.schema_migrations(version) VALUES($1)',[VERSION]);const check=await c.query(`SELECT (SELECT count(*) FROM public.platform_settings WHERE key='multichannel_homologation_allowlist')=1 AS allowlist, (SELECT count(*) FROM public.platform_settings WHERE key IN('multichannel_replication_enabled','social_to_tv_replication_enabled','social_crosspost_enabled','multichannel_auto_mode_enabled') AND value='false'::jsonb)=4 AS flags_off`);await c.query('COMMIT');return NextResponse.json({success:true,version:VERSION,verification:check.rows[0]})}catch(e:any){try{await c.query('ROLLBACK')}catch{}return NextResponse.json({success:false,error:e.message},{status:500})}finally{await c.end().catch(()=>undefined)}}
