import { redirect } from 'next/navigation';
import { getReferralDashboardAction } from '@/app/actions/referral-conversions';

const money = (value: unknown) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export default async function ReferralsPage() {
  const data = await getReferralDashboardAction();
  if (!data.success) redirect('/login');
  const funnel = data.creatorFunnel as any[];
  const stats = { leads: funnel.length, qualified: funnel.filter(x => ['qualified','proposal','converted'].includes(x.stage)).length, proposals: funnel.filter(x => ['proposal','converted'].includes(x.stage)).length, sales: funnel.filter(x => x.stage === 'converted').length };
  return <div className="mx-auto max-w-7xl space-y-7"><section className="rounded-3xl border border-purple-500/20 bg-gradient-to-br from-slate-950 to-purple-950/40 p-7"><p className="text-xs font-black uppercase tracking-[.2em] text-purple-400">MPM Fase 2</p><h1 className="mt-2 text-3xl font-black text-white">Creators & Indicações</h1><p className="mt-2 text-slate-400">Lead → Conversão → Comissão financeira, sem misturar Créditos MPM ou Direito de Mídia.</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><Flag on={data.flags.creator_referral_leads_enabled} label="Indicações"/><Flag on={data.flags.external_lead_api_enabled} label="API externa"/><Flag on={data.flags.commission_billing_enabled} label="Cobrança real"/><Flag on={data.flags.creator_cash_payout_enabled} label="Payout real"/></div></section>
  {data.creator && <section><h2 className="mb-3 text-xl font-black text-white">Minhas Indicações</h2><div className="grid gap-3 sm:grid-cols-4"><Metric label="Leads" value={stats.leads}/><Metric label="Qualificados" value={stats.qualified}/><Metric label="Propostas" value={stats.proposals}/><Metric label="Vendas" value={stats.sales}/></div><div className="mt-4 overflow-hidden rounded-2xl border border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3">Lead protegido</th><th>Campanha</th><th>Etapa</th><th>Comissão</th><th>Status</th></tr></thead><tbody>{funnel.map(row=><tr key={row.lead_id} className="border-t border-slate-800 text-slate-300"><td className="p-3">{row.masked_identifier}</td><td>{row.campaign_name}</td><td>{row.stage}</td><td>{money(row.creator_net)}</td><td>{row.commission_status || 'prevista'}</td></tr>)}</tbody></table>{!funnel.length&&<p className="p-7 text-center text-slate-500">Nenhuma indicação ainda.</p>}</div></section>}
  <section className="grid gap-6 lg:grid-cols-2"><div><h2 className="mb-3 text-xl font-black text-white">Links de indicação</h2><div className="space-y-3">{data.referrals.map((r:any)=><article key={r.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><b className="text-white">{r.campaigns?.name}</b><p className="text-sm text-slate-400">Creator: {r.creator_profiles?.display_name}</p><code className="mt-3 block rounded-lg bg-slate-950 p-2 text-purple-300">/r/{r.public_code}</code><a className="mt-3 inline-block text-sm font-bold text-purple-400" href={`/api/referrals/${r.public_code}/qr`}>Abrir QR Code</a></article>)}{!data.referrals.length&&<p className="rounded-2xl border border-dashed border-slate-700 p-7 text-slate-500">Os links surgem após aceite de oferta de indicação.</p>}</div></div><div><h2 className="mb-3 text-xl font-black text-white">Fechamentos</h2><div className="space-y-3">{data.closings.map((c:any)=><article key={c.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex justify-between"><b className="text-white">{c.franchises?.code}</b><span className="text-xs font-bold text-amber-300">{c.simulation_only?'SIMULADO':'REAL'} · {c.status}</span></div><p className="mt-2 text-sm text-slate-400">{c.period_start} a {c.period_end}</p><p className="mt-3 text-lg font-black text-white">{money(c.gross_amount)}</p><p className="text-xs text-slate-500">MPM {money(c.fee_amount)} · Creators {money(c.creator_net_amount)}</p></article>)}{!data.closings.length&&<p className="rounded-2xl border border-dashed border-slate-700 p-7 text-slate-500">Nenhum fechamento consolidado.</p>}</div></div></section>
  </div>;
}
function Metric({label,value}:{label:string;value:number}) { return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs uppercase text-slate-500">{label}</p><b className="text-2xl text-white">{value}</b></div>; }
function Flag({on,label}:{on:boolean;label:string}) { return <span className={`rounded-full border px-3 py-1 ${on?'border-emerald-500/30 text-emerald-300':'border-amber-500/30 text-amber-300'}`}>{label}: {on?'ON':'OFF'}</span>; }
