'use client';

import { useEffect, useMemo, useRef, useState, useTransition } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { BadgeCheck, CalendarClock, CircleDollarSign, Handshake, Megaphone, Network, ShieldCheck, Tv, Users } from 'lucide-react';
import { acceptCollaborativeOfferAction, createCollaborativeCampaignAction, setCollaborativeChannelAction } from '@/app/actions/collaborative-network';

const destinations = [
  ['ownTvs', 'Minhas TVs', Tv], ['ownInstagram', 'Meu Instagram', Network], ['ownFacebook', 'Meu Facebook', Network],
  ['ownTikTok', 'Meu TikTok (manual)', Network], ['collaborativeTvs', 'Rede de TVs', Tv],
  ['collaborativeBusinesses', 'Páginas Empresariais', Handshake], ['collaborativeCreators', 'Creators', Users],
] as const;
const blank = (companyId = '') => ({ companyId, name: '', description: '', startsOn: '', endsOn: '', rewardMode: 'mpm_credits', budgetTotal: 0, recurrence: 'once', ownTvs: true, ownInstagram: false, ownFacebook: false, ownTikTok: false, collaborativeTvs: false, collaborativeBusinesses: false, collaborativeCreators: false });

export default function CollaborativeNetworkClient({ initialData }: { initialData: any }) {
  const router = useRouter(); const params = useSearchParams();
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState('');
  const [saveState, setSaveState] = useState<'idle'|'saving'|'saved'|'error'>('idle');
  const [tab, setTab] = useState<'campaigns'|'opportunities'|'channels'>('campaigns');
  const [campaignId, setCampaignId] = useState<string|null>(null);
  const [form, setForm] = useState<any>(() => blank(initialData.companies[0]?.id || ''));
  const idempotencyKey = useRef(crypto.randomUUID());
  const enabled = Boolean(initialData.flags.collaborative_media_network_enabled);
  const companyIds = useMemo(() => new Set(initialData.companies.map((c:any)=>c.id)), [initialData.companies]);
  const participantChannels = useMemo(() => initialData.channels.filter((c:any)=>(c.owner_type==='creator'&&c.owner_id===initialData.creator?.id)||(c.owner_type==='company'&&companyIds.has(c.owner_id))), [initialData.channels, initialData.creator?.id, companyIds]);
  const creatorChannels = useMemo(() => participantChannels.filter((c:any)=>c.owner_type==='creator'), [participantChannels]);

  function fromCampaign(c:any) {
    const rules=c.campaign_distribution_rules||[]; const has=(type:string,provider?:string)=>rules.some((r:any)=>r.destination_type===type&&(!provider||r.provider===provider));
    return { companyId:c.company_id,name:c.name||'',description:c.description||'',startsOn:c.start_date||'',endsOn:c.end_date||'',rewardMode:c.reward_mode||'mpm_credits',budgetTotal:Number(c.budget_total||0),recurrence:rules[0]?.recurrence_type||'once',ownTvs:has('own_tv'),ownInstagram:has('own_social','instagram'),ownFacebook:has('own_social','facebook'),ownTikTok:has('own_social','tiktok'),collaborativeTvs:has('collaborative_tv'),collaborativeBusinesses:has('business_social'),collaborativeCreators:has('creator_social') };
  }
  useEffect(()=>{ const id=params.get('draft'); const c=initialData.campaigns.find((x:any)=>x.id===id&&x.status==='draft'); if(c){setCampaignId(c.id);setForm(fromCampaign(c));setSaveState('saved');} },[initialData.campaigns,params]);

  function validate(f:any) {
    if(!f.companyId)return 'Selecione a empresa anunciante.'; if(!f.name.trim())return 'Informe o nome da campanha antes de continuar.';
    if(Number(f.budgetTotal)<0)return 'O orçamento total não pode ser negativo.';
    if(f.startsOn&&f.endsOn&&f.endsOn<f.startsOn)return 'A data de término não pode ser anterior à data de início.';
    if(!destinations.some(([key])=>Boolean(f[key])))return 'Selecione ao menos um destino.'; return '';
  }
  async function saveDraft(next=form) {
    const invalid=validate(next); if(invalid){setMessage(invalid);setSaveState('error');return null;}
    setMessage('');setSaveState('saving');
    const r=await createCollaborativeCampaignAction({...next,campaignId:campaignId||undefined,idempotencyKey:idempotencyKey.current,budgetTotal:Number(next.budgetTotal)});
    if(!r.success){setMessage(r.error||'Falha ao salvar rascunho.');setSaveState('error');return null;}
    setCampaignId(r.campaignId);setSaveState('saved');router.replace(`/collaborative-network?draft=${r.campaignId}`,{scroll:false});router.refresh();return r.campaignId;
  }
  function toggle(key:string,checked:boolean){const next={...form,[key]:checked};setForm(next);if(checked&&['collaborativeTvs','collaborativeBusinesses','collaborativeCreators'].includes(key))startTransition(async()=>{await saveDraft(next);});}
  function edit(c:any){setCampaignId(c.id);setForm(fromCampaign(c));setSaveState('saved');setMessage('');router.replace(`/collaborative-network?draft=${c.id}`,{scroll:false});}

  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="rounded-3xl border border-purple-500/20 bg-gradient-to-br from-slate-950 via-slate-900 to-purple-950/30 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.22em] text-purple-400">MPM V1</p><h1 className="mt-1 text-2xl font-black text-white sm:text-3xl">Rede Colaborativa Multicanal</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">Uma campanha, vários destinos e o mesmo campaign_id.</p></div><div className={`rounded-full border px-4 py-2 text-xs font-black ${enabled?'border-emerald-500/30 bg-emerald-500/10 text-emerald-300':'border-amber-500/30 bg-amber-500/10 text-amber-300'}`}><ShieldCheck className="mr-2 inline h-4 w-4"/>{enabled?'PILOTO ATIVO':'ROLLOUT CONTROLADO PELO MASTER'}</div></div></div>
    <div className="flex gap-2 overflow-x-auto">{([['campaigns','Campanhas'],['opportunities','Oportunidades'],['channels','Minha Página na Rede']] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm font-bold ${tab===key?'bg-purple-600 text-white':'bg-slate-900 text-slate-400'}`}>{label}</button>)}</div>
    {message&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-200">{message}</div>}
    {tab==='campaigns'&&<div className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]">
      <form onSubmit={e=>{e.preventDefault();startTransition(async()=>{await saveDraft();});}} className="space-y-6 rounded-3xl border border-slate-800 bg-slate-900 p-4 sm:p-6">
        <div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black text-white">{campaignId?'Editar campanha multicanal':'Nova Campanha Multicanal'}</h2><p className="text-sm text-slate-500">Salva em rascunho sem publicar ou ativar.</p></div><span aria-live="polite" className={`text-xs font-bold ${saveState==='error'?'text-rose-400':'text-emerald-400'}`}>{saveState==='saving'?'Salvando…':saveState==='saved'?'Rascunho salvo':''}</span></div>
        <Field label="Empresa anunciante"><select required value={form.companyId} onChange={e=>setForm({...form,companyId:e.target.value})} className="input-dark">{initialData.companies.map((c:any)=><option key={c.id} value={c.id}>{c.trade_name}</option>)}</select></Field>
        <Field label="Nome da campanha"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Campanha de lançamento" className="input-dark"/></Field>
        <Field label="Objetivo e mensagem" help="Descreva o que será divulgado e o resultado esperado."><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="input-dark min-h-24"/></Field>
        <section><h3 className="mb-1 text-sm font-black text-white">Destinos da campanha</h3><p className="mb-3 text-xs text-slate-500">Marcar um destino apenas o inclui no rascunho; não publica a campanha.</p><div className="grid gap-2 sm:grid-cols-2">{destinations.map(([key,label,Icon])=><label key={key} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-800 bg-slate-950 p-3 text-sm text-slate-300"><input type="checkbox" checked={Boolean(form[key])} onChange={e=>toggle(key,e.target.checked)}/><Icon className="h-4 w-4 text-purple-400"/>{label}</label>)}</div></section>
        <section className="space-y-3 rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><div><h3 className="text-sm font-black text-white">Período da campanha</h3><p className="text-xs text-slate-500">As datas são opcionais enquanto estiver em rascunho.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Data de início" help="Quando a campanha poderá começar."><input type="date" value={form.startsOn} onChange={e=>setForm({...form,startsOn:e.target.value})} className="input-dark"/></Field><Field label="Data de término" help="Último dia previsto da campanha."><input type="date" min={form.startsOn||undefined} value={form.endsOn} onChange={e=>setForm({...form,endsOn:e.target.value})} className="input-dark"/>{form.startsOn&&form.endsOn&&form.endsOn<form.startsOn&&<span className="block text-xs font-bold text-rose-400">A data de término não pode ser anterior à data de início.</span>}</Field></div></section>
        <section className="space-y-3 rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><div><h3 className="text-sm font-black text-white">Distribuição e orçamento</h3><p className="text-xs text-slate-500">Configuração real do limite total reservado aos destinos colaborativos.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Frequência de distribuição"><select value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})} className="input-dark"><option value="once">Uma vez</option><option value="daily">Todos os dias</option><option value="weekly">Uma vez por semana</option><option value="specific_days">Dias específicos</option><option value="custom_period">Período personalizado</option></select></Field><Field label="Unidade do orçamento"><select value={form.rewardMode} onChange={e=>setForm({...form,rewardMode:e.target.value})} className="input-dark"><option value="mpm_credits">Créditos MPM</option><option value="media_rights">Direito de Mídia</option></select></Field></div><Field label="Orçamento total da campanha" help={`Limite da campanha em ${form.rewardMode==='media_rights'?'Direito de Mídia':'Créditos MPM'}. Zero é permitido no rascunho.`}><div className="relative"><input type="number" min="0" step="0.01" value={form.budgetTotal} onChange={e=>setForm({...form,budgetTotal:e.target.value})} className="input-dark pr-36"/><span className="pointer-events-none absolute inset-y-0 right-3 flex items-center text-xs font-bold text-slate-500">{form.rewardMode==='media_rights'?'Direito de Mídia':'Créditos MPM'}</span></div></Field></section>
        {campaignId&&<div className="flex flex-wrap gap-2">{form.collaborativeTvs&&<Link href={`/marketplace?tab=tvs&campaign_id=${campaignId}`} className="action-link">ESCOLHER TVs</Link>}{form.collaborativeCreators&&<Link href={`/marketplace?tab=creators&campaign_id=${campaignId}`} className="action-link">ESCOLHER CREATORS</Link>}{form.collaborativeBusinesses&&<button type="button" className="action-link" onClick={()=>setMessage('Rascunho preservado. Configure Páginas Empresariais na revisão da campanha.')}>CONFIGURAR PÁGINAS</button>}</div>}
        <div className="flex flex-col gap-3 sm:flex-row"><button disabled={pending} className="flex-1 rounded-xl bg-purple-600 px-5 py-3 font-black text-white disabled:opacity-40">{pending?'Salvando…':'SALVAR RASCUNHO'}</button>{campaignId&&<Link href={`/campaigns/${campaignId}`} className="rounded-xl border border-slate-700 px-5 py-3 text-center font-black text-white">REVISAR CAMPANHA</Link>}</div>
        {!enabled&&<div className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-sm text-amber-200"><b>Campanha salva como rascunho.</b><br/>Status: Aguardando liberação do Master. A montagem e a revisão continuam disponíveis; somente a ativação permanece bloqueada.</div>}
      </form>
      <div className="space-y-3"><h2 className="text-xl font-black text-white">Campanhas</h2>{initialData.campaigns.length===0?<Empty text="Nenhuma campanha multicanal criada."/>:initialData.campaigns.map((c:any)=>{const b=c.collaborative_campaign_budget_summary?.[0]||{};return <div key={c.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex justify-between gap-3"><div><h3 className="font-bold text-white">{c.name}</h3><p className="text-xs text-slate-500">{c.status==='draft'?'RASCUNHO':c.status} · {c.start_date||'Sem início'} → {c.end_date||'Sem término'}</p></div><Megaphone className="h-5 w-5 text-purple-400"/></div><div className="mt-4 grid grid-cols-2 gap-2 text-center text-xs sm:grid-cols-4"><Metric label="Total" value={b.total??c.budget_total}/><Metric label="Disponível" value={b.available??c.budget_total}/><Metric label="Reservado" value={b.reserved??0}/><Metric label="Consumido" value={b.consumed??0}/></div>{c.status==='draft'&&<button onClick={()=>edit(c)} className="mt-4 text-xs font-black text-purple-400">CONTINUAR EDIÇÃO</button>}</div>})}</div>
    </div>}
    {tab==='opportunities'&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{initialData.offers.length===0?<Empty text="Nenhuma oportunidade elegível agora."/>:initialData.offers.map((o:any)=><div key={o.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-xs font-black uppercase text-purple-400">{o.offer_type==='open'?'Oferta aberta':'Oferta direcionada'}</p><h3 className="mt-1 text-lg font-black text-white">{o.campaigns?.name}</h3><p className="text-sm text-slate-400">{o.campaigns?.companies?.trade_name}</p><div className="mt-4 space-y-2 text-sm text-slate-300"><p><BadgeCheck className="mr-2 inline h-4 w-4 text-emerald-400"/>{o.format}</p><p><CircleDollarSign className="mr-2 inline h-4 w-4 text-amber-400"/>{o.reward_amount} {o.reward_mode==='media_rights'?'Direito de Mídia':'Créditos MPM'}</p><p><CalendarClock className="mr-2 inline h-4 w-4 text-sky-400"/>{o.total_slots-o.accepted_slots} vagas restantes</p></div><button disabled={pending||!initialData.creator} onClick={()=>startTransition(async()=>{const r=await acceptCollaborativeOfferAction(o.id,'creator',initialData.creator.id,creatorChannels[0]?.id);setMessage(r.success?'Oferta aceita e orçamento reservado.':r.error||'Falha.');router.refresh();})} className="mt-5 w-full rounded-xl bg-purple-600 py-2.5 text-sm font-black text-white disabled:opacity-40">ACEITAR OFERTA</button></div>)}</div>}
    {tab==='channels'&&<div className="space-y-4"><h2 className="text-xl font-black text-white">Participar da Rede Colaborativa</h2>{participantChannels.length===0?<Empty text="Nenhum canal Creator ou Empresa conectado para configurar."/>:participantChannels.map((c:any)=><ChannelCard key={c.id} channel={c} pending={pending} onSave={(input:any)=>startTransition(async()=>{const r=await setCollaborativeChannelAction(input);setMessage(r.success?'Canal atualizado.':r.error||'Falha.');router.refresh();})}/>)}</div>}
    <style jsx global>{`.input-dark{width:100%;border-radius:.75rem;border:1px solid rgb(51 65 85);background:rgb(2 6 23);padding:.75rem;color:white;font-size:.875rem}.action-link{border-radius:.75rem;background:rgb(30 41 59);padding:.65rem 1rem;color:white;font-size:.75rem;font-weight:900}`}</style>
  </div>;
}
function Field({label,help,children}:{label:string;help?:string;children:React.ReactNode}){return <label className="block space-y-1.5"><span className="block text-sm font-bold text-slate-200">{label}</span>{children}{help&&<span className="block text-xs leading-relaxed text-slate-500">{help}</span>}</label>}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-lg bg-slate-950 p-2"><p className="text-slate-500">{label}</p><b className="text-white">{Number(value||0).toLocaleString('pt-BR')}</b></div>}
function Empty({text}:{text:string}){return <div className="col-span-full rounded-2xl border border-dashed border-slate-700 bg-slate-900/50 p-10 text-center text-sm text-slate-500">{text}</div>}
function ChannelCard({channel,pending,onSave}:{channel:any;pending:boolean;onSave:(input:any)=>void}){const [active,setActive]=useState(Boolean(channel.participation_enabled));const formats=channel.provider==='tiktok'?['tiktok_video']:['story','feed','reel'];return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-black text-white">{channel.display_name}</h3><p className="text-xs uppercase text-slate-500">{channel.owner_type==='creator'?'Creator':'Empresa'} · {channel.provider}</p></div><label className="flex items-center gap-2 text-sm font-bold text-slate-300"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Participar</label></div><button disabled={pending} onClick={()=>onSave({channelId:channel.id,ownerType:channel.owner_type,ownerId:channel.owner_id,enabled:active,formats,monthlyLimit:4,minimumReward:0,approvalMode:'manual'})} className="mt-4 rounded-xl bg-slate-800 px-4 py-2 text-xs font-black text-white">Salvar opt-in</button></div>}
